#!/usr/bin/env php
<?php
include 'bootstrap/app.php';

use Console\HashCommand;
use Console\RunTestCommand;
use Symfony\Component\Console\Application;


$application = new Application();
$application->add(new HashCommand());
$application->add(new RunTestCommand());
$application->add(new \Console\MakeControllerCommand());
$application->run();
