#!/usr/bin/env php
<?php
if (PHP_SAPI !== 'cli') {
    exit (1);
}
include 'bootstrap/app.php';


$container = $app->getContainer();

$directory = New \Kernel\Helpers\DirectoryHelper();
$command = $directory->scan('console');

$exceptions = [
    'route list '=>'Console\RoutesListCommand'
];

$commands_map = array_map(function($k) {
    $k = 'Console\\'.$k;
    return str_replace('.php', '', $k);
}, $command);

foreach($commands_map as $com){
    if(in_array($com , $exceptions)){
        continue;
    }
    $commands[] = $com;
}


$application = new \Symfony\Component\Console\Application();
foreach ($commands as $class) {
    if (!class_exists($class)) {
        throw new RuntimeException(sprintf('Class %s does not exist', $class));
    }
    $command = new $class();
    if (method_exists($command, 'setContainer')) {
        $command->setContainer($container);
    }
    $application->add($command);
}

foreach($exceptions as $key=>$expClass){
    if (!class_exists($class)) {
        throw new RuntimeException(sprintf('Class %s does not exist', $class));
    }


    $command = new $expClass($key,$app);
    if (method_exists($command, 'setContainer')) {
        $command->setContainer($container);
    }
    $application->add($command);
}


$output = new Symfony\Component\Console\Output\ConsoleOutput();
$style = new Symfony\Component\Console\Formatter\OutputFormatterStyle('blue', null, array('bold'));
$output->getFormatter()->setStyle('header', $style);



$application->run();