version: '3'
services:
  mysql:
    image: mariadb:latest
    volumes:
      - "./.docker/.data/db:/var/lib/mysql"
      - "./.docker/data/import.sh:/tmp/import.sh"
    restart: always
    ports:
      - "4444:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bonsai
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: mysqld --user=root --verbose
    env_file:
      - ".env"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "3333:6379"
  phpfpm:
#    image: php:72-fpm
    build:
      context: '.'
      dockerfile: .docker/config/php-fpm/Dockerfile
    depends_on:
      - mysql
      - redis
    volumes:
      - "./:/var/www/html"
      - "./.docker/config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./.docker/config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "./.docker/config/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf"
    restart: always
    command: 'php bonsai migrate'
  nginx:
    depends_on:
      - phpfpm
    ports:
      - "8001:80"
    image: nginx:latest
    volumes:
      - "./:/var/www/html"
      - "./.docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./.docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf"
    restart: always
  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - .:/var/www/html/
#    command: "install --ignore-platform-reqs"