version: '2'
services:
  mysql:
    image: mariadb:latest
    container_name: db
    volumes:
      - "./.docker/.data/db:/var/lib/mysql"
#     - "./.docker/data/import.sh:/tmp/import.sh"
      - ./.docker/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "4444:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bonsai2
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --init-file /docker-entrypoint-initdb.d/init.sql

    env_file:
      - ".env"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6333:6379"
  phpfpm:
#    image: php:7.1-fpm-alpine
    build:
      context: '.'
      dockerfile: .docker/config/php-fpm/Dockerfile
    depends_on:
      - mysql
      - redis
    volumes:
      - "./:/var/www/html"
      - "./.docker/config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./.docker/config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "./.docker/config/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf"
    restart: always
    command: "php bonsai migrate"
  nginx:
    container_name: web
    depends_on:
      - phpfpm
    ports:
      - "8001:80"
    image: nginx:latest
    volumes:
      - "./:/var/www/html"
      - "./.docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./.docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf"
    restart: always
  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - .:/var/www/html/