version: '2'
services:
  mysql:
    image: mariadb:latest
    volumes:
      - "./.docker/.data/db:/var/lib/mysql"
      - "./.docker/import.sh:/tmp/import.sh"

    restart: always
    ports:
      - "55555:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bonsai
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: mysqld --user=root --verbose
  redis:
    image: redis:latest
    restart: always
    ports:
      - "44444:6379"
  phpfpm:
    image: php:7-fpm
    depends_on:
      - mysql
      - redis
    volumes:
      - "./:/var/www/html"
      - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini"
    restart: always
    command: 'php bonsai migrate:up'
  nginx:
    depends_on:
      - phpfpm
    ports:
      - "8001:80"
    image: nginx:latest
    volumes:
      - "./:/var/www/html"
      - "./.docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./.docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf"
    restart: always
    tty: true
  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - .:/var/www/html/
#    command: "install --ignore-platform-reqs"
  app:
      build:
        context: .
        dockerfile: .docker/config/php-fpm/Dockerfile